// Offline-only post-FACE6 placement planner.  No controller clients are created.
#include <algorithm>
#include <cmath>
#include <cstdlib>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <stdexcept>
#include <vector>

#include <Eigen/Geometry>
#include <geometry_msgs/msg/pose.hpp>
#include <moveit/collision_detection/collision_common.h>
#include <moveit/planning_scene/planning_scene.h>
#include <moveit/robot_model_loader/robot_model_loader.h>
#include <moveit/robot_state/robot_state.h>
#include <moveit_msgs/msg/collision_object.hpp>
#include <rclcpp/rclcpp.hpp>
#include <shape_msgs/msg/solid_primitive.hpp>
#include <yaml-cpp/yaml.h>

namespace {
const std::vector<std::string> A={"arm_a_j1","arm_a_j2","arm_a_j3","arm_a_j4","arm_a_j5","arm_a_j6"};
const std::vector<std::string> B={"arm_b_j1","arm_b_j2","arm_b_j3","arm_b_j4","arm_b_j5","arm_b_j6"};
constexpr char TCP[]="arm_b_gripper_tcp";
struct Seg { std::string id,method; std::vector<std::vector<double>> q; };
void set(moveit::core::RobotState&s,const std::vector<std::string>&n,const std::vector<double>&q){for(size_t i=0;i<n.size();++i)s.setVariablePosition(n[i],q[i]);s.update();}
std::vector<double> get(const moveit::core::RobotState&s,const std::vector<std::string>&n){std::vector<double>q;for(auto&x:n)q.push_back(s.getVariablePosition(x));return q;}
geometry_msgs::msg::Pose target(double z){geometry_msgs::msg::Pose p;p.position.x=-.450000000776;p.position.y=.399999997171;p.position.z=z;p.orientation.x=.707106781175;p.orientation.y=.707106781198;p.orientation.z=-.000000000034;p.orientation.w=-.000000000035;return p;}
bool valid(planning_scene::PlanningScene&sc,moveit::core::RobotState&s,std::string&why){collision_detection::CollisionRequest r;collision_detection::CollisionResult out;r.contacts=true;r.max_contacts=10;r.max_contacts_per_pair=1;sc.checkCollision(r,out,s);if(!s.satisfiesBounds()){why="joint_bounds";return false;}if(!out.collision)return true;why=out.contacts.empty()?"collision":out.contacts.begin()->first.first+" <-> "+out.contacts.begin()->first.second;return false;}
bool ik(moveit::core::RobotState&s,const moveit::core::JointModelGroup*g,const geometry_msgs::msg::Pose&p){return s.setFromIK(g,p,TCP,.5);}
bool robustIk(moveit::core::RobotState& s,const moveit::core::JointModelGroup* g,const geometry_msgs::msg::Pose& p){ return ik(s,g,p); }
geometry_msgs::msg::Pose asPose(const Eigen::Isometry3d& t){geometry_msgs::msg::Pose p;Eigen::Quaterniond q(t.linear());p.position.x=t.translation().x();p.position.y=t.translation().y();p.position.z=t.translation().z();p.orientation.x=q.x();p.orientation.y=q.y();p.orientation.z=q.z();p.orientation.w=q.w();return p;}
void printPose(const char* n,const Eigen::Isometry3d& t){auto p=asPose(t);std::cout<<n<<" xyz=["<<p.position.x<<", "<<p.position.y<<", "<<p.position.z<<"] xyzw=["<<p.orientation.x<<", "<<p.orientation.y<<", "<<p.orientation.z<<", "<<p.orientation.w<<"]"<<std::endl;}
void printJoints(const char* n,const std::vector<double>& q){std::cout<<n<<" joints_rad=[";for(size_t i=0;i<q.size();++i)std::cout<<(i?", ":"")<<q[i];std::cout<<"]"<<std::endl;}
bool jointPath(planning_scene::PlanningScene&sc,const moveit::core::RobotModelConstPtr&m,const std::vector<double>&a,const std::vector<double>&from,const std::vector<double>&to,Seg&o,std::string&why){double d=0;for(int j=0;j<6;j++)d=std::max(d,std::abs(to[j]-from[j]));int n=std::max(2,(int)std::ceil(d/.025));for(int k=0;k<=n;k++){std::vector<double>q(6);for(int j=0;j<6;j++)q[j]=from[j]+(to[j]-from[j])*(double)k/n;moveit::core::RobotState s(m);s.setToDefaultValues();set(s,A,a);set(s,B,q);if(!valid(sc,s,why))return false;o.q.push_back(q);}return true;}
bool cartPath(planning_scene::PlanningScene&sc,const moveit::core::RobotModelConstPtr&m,const moveit::core::JointModelGroup*g,const std::vector<double>&a,const std::vector<double>&seed,double z0,double z1,Seg&o,std::string&why){moveit::core::RobotState s(m);s.setToDefaultValues();set(s,A,a);set(s,B,seed);for(int k=0;k<=20;k++){auto p=target(z0+(z1-z0)*k/20.);if(!robustIk(s,g,p)){why="IK sample "+std::to_string(k);return false;}s.update();if((s.getGlobalLinkTransform(TCP).translation()-Eigen::Vector3d(p.position.x,p.position.y,p.position.z)).norm()>1e-4){why="FK error";return false;}if(!valid(sc,s,why))return false;o.q.push_back(get(s,B));}return true;}
void vec(std::ostream&o,const std::vector<double>&q){const auto old=o.precision();o<<std::setprecision(12)<<"[";for(size_t i=0;i<q.size();++i)o<<(i?", ":"")<<q[i];o<<"]";o<<std::setprecision(old);}
void emit(std::ostream&o,const Seg&s){o<<"  - id: "<<s.id<<"\n    kind: joint_connection\n    moving: arm_b\n    method: "<<s.method<<"\n    status: PASS\n    joint_names: [arm_b_j1, arm_b_j2, arm_b_j3, arm_b_j4, arm_b_j5, arm_b_j6]\n    start_joints: ";vec(o,s.q.front());o<<"\n    end_joints: ";vec(o,s.q.back());o<<"\n    points:\n";for(size_t i=0;i<s.q.size();++i){const auto ns=i*50000000ULL;o<<"    - positions: ";vec(o,s.q[i]);o<<"\n      sec: "<<ns/1000000000ULL<<"\n      nanosec: "<<ns%1000000000ULL<<"\n      velocities: [0, 0, 0, 0, 0, 0]\n      accelerations: [0, 0, 0, 0, 0, 0]\n";}}
}
int main(int argc,char**argv){rclcpp::init(argc,argv);auto node=std::make_shared<rclcpp::Node>("keypose_v1_b_place_candidate");const std::string root=std::string(getenv("HOME"))+"/fr_task_ws/src/fr_task_planner",src=root+"/config/keypose_v1_six_face_trajectory.yaml";auto y=YAML::LoadFile(src);std::vector<double>q0,a;for(auto s:y["stages"])if(s["id"].as<std::string>()=="face5_to_face6")for(auto v:s["end_joints"])q0.push_back(v.as<double>());for(auto v:y["home_a"])a.push_back(v.as<double>());if(q0.size()!=6)throw std::runtime_error("FACE6 missing");robot_model_loader::RobotModelLoader loader(node);auto m=loader.getModel();auto g=m->getJointModelGroup("arm_b");auto sc=std::make_shared<planning_scene::PlanningScene>(m);
// A local table only: its collision checking is never globally disabled or published.
moveit_msgs::msg::CollisionObject table;table.id="table";table.header.frame_id="world";table.operation=table.ADD;table.primitives.resize(1);table.primitives[0].type=shape_msgs::msg::SolidPrimitive::BOX;table.primitives[0].dimensions={2.,2.,.05};table.primitive_poses.resize(1);table.primitive_poses[0].position.z=.725;table.primitive_poses[0].orientation.w=1.;sc->processCollisionObjectMsg(table);
moveit::core::RobotState st(m);st.setToDefaultValues();set(st,A,a);set(st,B,q0);std::cout<<"IK group=arm_b planning_frame="<<m->getModelFrame()<<" requested_tip="<<TCP<<" group_links=";for(const auto&l:g->getLinkModelNames())std::cout<<l<<",";std::cout<<std::endl;printPose("FACE6 TCP FK",st.getGlobalLinkTransform(TCP));auto face6_pose=asPose(st.getGlobalLinkTransform(TCP));auto inverse=st;if(!ik(inverse,g,face6_pose))std::cerr<<"FACE6 FK_TO_IK_FAIL\n";else printPose("FACE6 FK_TO_IK TCP",inverse.getGlobalLinkTransform(TCP));std::vector<double> pre;for(auto v:y["home_b"])pre.push_back(v.as<double>());set(st,B,pre);printJoints("PRE_PLACE HOME",pre);printPose("PRE_PLACE FK",st.getGlobalLinkTransform(TCP));const auto pt=target(.875499997974);const double pre_err=(st.getGlobalLinkTransform(TCP).translation()-Eigen::Vector3d(pt.position.x,pt.position.y,pt.position.z)).norm();const bool pre_ok=pre_err<1e-5;std::cout<<"PRE_PLACE FK position_error_m="<<pre_err<<std::endl;moveit::core::RobotState place(st);printPose("PLACE requested",Eigen::Translation3d(-.450000000776,.399999997171,.775499997974)*Eigen::Quaterniond(-.000000000035,.707106781175,.707106781198,-.000000000034));const bool place_ok=robustIk(place,g,target(.775499997974));if(place_ok){printJoints("PLACE IK",get(place,B));printPose("PLACE FK",place.getGlobalLinkTransform(TCP));}else std::cerr<<"PLACE IK FAIL\n";if(!pre_ok||!place_ok)return 3;Seg c{"face6_to_pre_place","moveit_collision_checked_joint_connection"},d{"pre_place_to_place","moveit_seeded_cartesian_world_negative_z"},u{"place_to_retreat","moveit_seeded_cartesian_world_positive_z"};std::string why;if(!jointPath(*sc,m,a,q0,pre,c,why)){std::cerr<<"FACE6 connection FAIL "<<why<<"\n";return 5;}if(!cartPath(*sc,m,g,a,pre,.875499997974,.775499997974,d,why)){std::cerr<<"DESCENT FAIL "<<why<<"\n";return 6;}if(!cartPath(*sc,m,g,a,d.q.back(),.775499997974,.875499997974,u,why)){std::cerr<<"RETREAT FAIL "<<why<<"\n";return 7;}
const auto dst=root+"/config/keypose_optimization_v1/keypose_v1_six_face_with_place_candidate.yaml";std::ifstream in(src);std::ofstream out(dst);out<<"# Offline-only complete candidate; source sequence copied verbatim below.\n"<<in.rdbuf()<<"\n";emit(out,c);emit(out,d);out<<"  - id: gripper_open_b_place\n    kind: gripper_open_event\n    moving: arm_b\n    status: PASS\n    execution: false\n    owner_before: B\n    owner_after: world\n    object_id: small_part\n    object_center_world: [-0.450000000776, 0.399999997171, 0.767499997974]\n    object_bottom_z: 0.750000000000\n    q_b: 0.0\n";emit(out,u);out<<"complete_candidate: true\npre_place_tcp: [-0.450000000776, 0.399999997171, 0.875499997974]\nplace_tcp: [-0.450000000776, 0.399999997171, 0.775499997974]\n";
std::ofstream rep(root+"/config/keypose_optimization_v1/b_place_offline_report.yaml");rep<<"result: PASS\nsource_frozen_unchanged: true\nface6_to_pre_place: {status: PASS, points: "<<c.q.size()<<", method: moveit_collision_checked_joint_connection}\npre_place_to_place: {status: PASS, points: "<<d.q.size()<<", direction_world: [0, 0, -0.100]}\ngripper_open_b_place: {status: PASS, attached_to_world_transition: true}\nplace_to_retreat: {status: PASS, points: "<<u.q.size()<<", direction_world: [0, 0, 0.100]}\nobject_center_final: [-0.450000000776, 0.399999997171, 0.767499997974]\nobject_bottom_z: 0.750\n";std::cout<<"PLACE_CANDIDATE_PASS "<<dst<<std::endl;rclcpp::shutdown();}
