// Read-only offline validation of the two software-synchronised handover stages.
#include <cmath>
#include <fstream>
#include <iostream>
#include <rclcpp/rclcpp.hpp>
#include <yaml-cpp/yaml.h>
#include <moveit/collision_detection/collision_common.h>
#include <moveit/planning_scene/planning_scene.h>
#include <moveit/robot_model_loader/robot_model_loader.h>
#include <moveit_msgs/msg/attached_collision_object.hpp>
#include <moveit_msgs/srv/get_planning_scene.hpp>
#include <shape_msgs/msg/solid_primitive.hpp>

namespace {
const std::vector<std::string> A={"arm_a_j1","arm_a_j2","arm_a_j3","arm_a_j4","arm_a_j5","arm_a_j6"};
const std::vector<std::string> B={"arm_b_j1","arm_b_j2","arm_b_j3","arm_b_j4","arm_b_j5","arm_b_j6"};
double t(const YAML::Node&p){return p["sec"].as<double>()+1e-9*p["nanosec"].as<double>();}
std::vector<double> q(const YAML::Node& p){std::vector<double>x;for(auto v:p["positions"])x.push_back(v.as<double>());return x;}
std::vector<double> at(const YAML::Node& ps,double x){size_t j=1;while(j<ps.size()&&t(ps[j])<x)++j;if(j==ps.size())return q(ps[ps.size()-1]);auto a=q(ps[j-1]),b=q(ps[j]);double u=(x-t(ps[j-1]))/(t(ps[j])-t(ps[j-1]));for(size_t i=0;i<6;++i)a[i]+=u*(b[i]-a[i]);return a;}
void set(moveit::core::RobotState&s,const std::vector<std::string>&n,const std::vector<double>&v){for(size_t i=0;i<6;++i)s.setVariablePosition(n[i],v[i]);s.update();}
bool attach(planning_scene::PlanningScene& sc,bool on_b){moveit_msgs::msg::AttachedCollisionObject rm;rm.link_name=on_b?"arm_a_gripper_tcp":"arm_b_gripper_tcp";rm.object.id="small_part";rm.object.operation=rm.object.REMOVE;sc.processAttachedCollisionObjectMsg(rm);moveit_msgs::msg::AttachedCollisionObject a;a.link_name=on_b?"arm_b_gripper_tcp":"arm_a_gripper_tcp";a.touch_links=on_b?std::vector<std::string>{"arm_b_gripper_base_link","arm_b_rail_155","arm_b_slider_l","arm_b_slider_r","arm_b_finger_l","arm_b_finger_r","arm_b_gripper_gap_link"}:std::vector<std::string>{"arm_a_gripper_base_link","arm_a_rail_155","arm_a_slider_l","arm_a_slider_r","arm_a_finger_l","arm_a_finger_r","arm_a_gripper_gap_link"};a.object.id="small_part";a.object.header.frame_id=a.link_name;a.object.operation=a.object.ADD;a.object.primitives.resize(1);a.object.primitives[0].type=shape_msgs::msg::SolidPrimitive::CYLINDER;a.object.primitives[0].dimensions={.035,.0075};geometry_msgs::msg::Pose p;p.orientation.w=1;a.object.primitive_poses={p};sc.processAttachedCollisionObjectMsg(a);return sc.getCurrentState().hasAttachedBody("small_part");}
bool stage(planning_scene::PlanningScene& sc,const YAML::Node& s,std::ostream&o){auto pa=s["arm_a"]["points"],pb=s["arm_b"]["points"];double d=t(pa[pa.size()-1]);if(std::abs(d-t(pb[pb.size()-1]))>1e-6){o<<"TIMEBASE_FAIL\n";return false;}auto acm=sc.getAllowedCollisionMatrix();acm.setEntry("small_part",std::vector<std::string>{"arm_a_gripper_base_link","arm_a_rail_155","arm_a_slider_l","arm_a_slider_r","arm_a_finger_l","arm_a_finger_r","arm_a_gripper_gap_link"},true);size_t checked=0;for(double x=0;x<d+1e-9;x+=.02){auto st=sc.getCurrentState();set(st,A,at(pa,x));set(st,B,at(pb,x));collision_detection::CollisionRequest r;r.contacts=true;r.max_contacts=20;r.max_contacts_per_pair=1;collision_detection::CollisionResult out;sc.checkCollision(r,out,st,acm);if(!st.satisfiesBounds()||out.collision){o<<"COLLISION_OR_BOUND_FAIL stage="<<s["id"].as<std::string>()<<" t="<<x;for(auto &c:out.contacts)o<<" "<<c.first.first<<"<->"<<c.first.second;o<<"\n";return false;}++checked;}o<<"PASS stage="<<s["id"].as<std::string>()<<" samples="<<checked<<" duration="<<d<<"\n";return true;}
}
int main(int argc,char**argv){rclcpp::init(argc,argv);auto n=std::make_shared<rclcpp::Node>("keypose_v1_sync_handover_validate");std::string path=std::string(std::getenv("HOME"))+"/fr_task_sync_ws/src/fr_task_planner/config/keypose_optimization_v1/keypose_v1_six_face_with_sync_handover_candidate.yaml";if(n->has_parameter("trajectory"))path=n->get_parameter("trajectory").as_string();auto loader=robot_model_loader::RobotModelLoader(n);auto model=loader.getModel();if(!model){std::cerr<<"MODEL_FAIL\n";return 2;}auto c=n->create_client<moveit_msgs::srv::GetPlanningScene>("/get_planning_scene");if(!c->wait_for_service(std::chrono::seconds(3))){std::cerr<<"GET_SCENE_UNAVAILABLE\n";return 3;}auto req=std::make_shared<moveit_msgs::srv::GetPlanningScene::Request>();req->components.components=moveit_msgs::msg::PlanningSceneComponents::WORLD_OBJECT_GEOMETRY|moveit_msgs::msg::PlanningSceneComponents::ROBOT_STATE_ATTACHED_OBJECTS|moveit_msgs::msg::PlanningSceneComponents::ALLOWED_COLLISION_MATRIX;auto f=c->async_send_request(req);if(rclcpp::spin_until_future_complete(n,f,std::chrono::seconds(5))!=rclcpp::FutureReturnCode::SUCCESS){std::cerr<<"GET_SCENE_TIMEOUT\n";return 3;}planning_scene::PlanningScene sc(model);sc.setPlanningSceneMsg(f.get()->scene);auto y=YAML::LoadFile(path);bool ok=true;for(auto s:y["stages"])if(s["kind"].as<std::string>()=="dual_joint_connection"){bool on_b=s["id"].as<std::string>().find("a_handover_to_home")!=std::string::npos;if(!attach(sc,on_b)){std::cerr<<"ATTACH_FAIL\n";return 4;}ok=stage(sc,s,std::cout)&&ok;}std::ofstream r("/tmp/sync_handover_collision_report.txt");r<<(ok?"SYNC_HANDOVER_COLLISION_PASS\n":"SYNC_HANDOVER_COLLISION_FAIL\n");std::cout<<(ok?"SYNC_HANDOVER_COLLISION_PASS\n":"SYNC_HANDOVER_COLLISION_FAIL\n");rclcpp::shutdown();return ok?0:5;}
